name: Build

on:
  pull_request: ~
  push: ~
  schedule:
    - cron: 42 5 * * 0
  workflow_dispatch: ~

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: perl build.pl
      
    - name: nm
      run: nm perl4mirc.dll      

    - uses: actions/upload-artifact@v4
      with:
        name: dll
        path: perl4mirc.dll
        
    - uses: actions/upload-artifact@v4
      with:
        name: zip
        path: perl4mIRC-1.5012002.zip
